### ISSUE TITLE
PHPDoc variable declaration/use statement order

### ISSUE THREAD

**Issue by chriscpty** [insperedia/yiidea-support#23] opened 2024-08-12 12:35 UTC
In the projects I work on, we always put the PHPDoc variable declarations below the use statements:

```php
use \foo\bar\Baz;

/**
* @var Baz $baz
*/
```

yiidea-support's "Missed PhpDoc variable declaration" inspection throws a warning as it seems to only consider PHPDocs that are at the very top of the file, before any `use` statements, meaning we have to either disable the inspection or restructure all the view files to have the variable declarations before the use statements.

Perhaps the inspection should also consider variable declarations that come after `use` (and similar) statements?

**Comment by insperedia** [comment] 2024-08-12 12:36
Thank you for the issue. I will take a look on the problem.

**Comment by insperedia** [comment] 2024-08-31 09:47
I can not reproduce the problem. The plugin supports multiline variable declarations after use declaration.
The problem is somewhere else. Try to press Add missed variable declarations to see what types and variables will be inserted.

**Comment by chriscpty** [comment] 2024-09-02 09:09
I can't reproduce it anymore either, maybe it either got fixed in the meantime or i got confused because yiidea-support seems to expect there to be an `@var yii\web\View $this` in the variable declarations, which I usually don't bother adding to views.

**Closed as completed** 2024-10-02 11:36 UTC

**Comment by verifiera** [comment] 2024-10-02 11:56
> I can't reproduce it anymore either, maybe it either got fixed in the meantime or i got confused because yiidea-support seems to expect there to be an `@var yii\web\View $this` in the variable declarations, which I usually don't bother adding to views.

The latter is correct.
