### ISSUE TITLE
Detect view files of template engines

### ISSUE THREAD

**Issue by Sandritsch91** [insperedia/yiidea-support#5] opened 2024-02-14 08:11 UTC
Thank you for updating this amazing plugin!

We use smarty as templating engine.
It would be great if the plugin could detect if the view file exists as a .tpl or .twig etc.

![image](https://github.com/insperedia/yiidea-support/assets/17873124/58a83e35-902d-4da8-966f-cc2f85f42e51)

![image](https://github.com/insperedia/yiidea-support/assets/17873124/cd4f1200-647a-4402-bdbc-c1bc9dd01e28)

Thanks again for your work, it makes working with yii2 so much easier!

**Comment by insperedia** [comment] 2024-02-15 19:56
Did you tried to set in settings your templating language?
Settings > Yii Framework Support > Views > Default View File Extension

**Comment by insperedia** [comment] 2024-02-15 20:02
The plugin supports any extension.
I think the problem is somewhere else. For example, there is a known bug with modules I am working with now.
Please give a path to your controller and views from the root of the project.

**Comment by Sandritsch91** [comment] 2024-02-16 08:17
> Did you tried to set in settings your templating language? Settings > Yii Framework Support > Views > Default View File Extension

Tried that, unfortunately it did not help



> The plugin supports any extension. I think the problem is somewhere else. For example, there is a known bug with modules I am working with now. Please give a path to your controller and views from the root of the project.

It is a module in a separate repository, so maybe that is the same problem.
Repository look like so:
- Root
  - src
    - controllers
    - migrations
    - models
    - views
    - ...
    - Module.php
- vendor
- composer.json

Hope that helps.
Greetings

**Comment by insperedia** [comment] 2024-02-16 08:42
Thank you. this use case currently I am working on and update is in testing already. Stay tune for update. Current estimation - 1 week

**Comment by Sandritsch91** [comment] 2024-02-16 09:48
Nice, thanks again for your work

**Comment by insperedia** [comment] 2024-02-22 11:55
Fixed in 1.0.8

**Closed as completed by insperedia** 2024-02-22 11:55 UTC

**Comment by isedwards** [comment] 2024-04-27 08:55
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
KenMan79, @venkatesh-1729, @iandeng, @OneWalletToRuleThemAll, @dipaksaraf, @oraix, @jgh004, @ashwinp-r, @partylikeits1983, @Locustsgogogo, @sapgan, @eikea12, @ma7dy, @yonghanlee, @ulswww, @charkala, @moritzmla, @fpmoney, @dno15x, @ritvanh, @W1Real, @massais, @KingCrab1990, @evrospower, @floydspace, @sjzlida, @Armandpl, @drewlustro, @playfund, @JordanLittell, @sgf, @null-dev, @arunlodhi, @dholtdev, @ClayReyn, @llorrac1, @mosunchao, @ZheArvin, @McMullenCoaching, @ssergio198, @lpj0017, @javifalces, @hoyah, @rongzhang, @frankfanslc, @dobrik, @hiyorijl, @shimamura33, @rchamorro, @t4ktik
